version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - C:/Users/atope/.ollama:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped

  web:
    build: .
    container_name: ollama-ui
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - OLLAMA_API_HOST=http://ollama:11434
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  ollama_data:
